# Generated by Django 6.0.7 on 2026-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
