# Generated by Django 6.0.7 on 2026-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_learningpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
